file(STRINGS ${CMAKE_CURRENT_LIST_DIR}/../version.txt PROJECT_VER LIMIT_COUNT 1)
string(STRIP "${PROJECT_VER}" PROJECT_VER)

idf_component_register(
        SRCS
            "esp_cam.c"
            "components/config/config.h"
            "components/wifi/wifi.h"
            "components/wifi/wifi.c"
            "components/camera/camera.h"
            "components/camera/camera.c"
            "components/sdcard/sdcard.h"
            "components/sdcard/sdcard.c"
            "components/http_server/http_server.h"
            "components/http_server/http_server.c"
            "components/utils/utils.h"
            "components/dns/dns.h"
            "components/dns/dns.c"
            "components/nvs/nvs.h"
            "components/nvs/nvs.c"
            "components/torch/torch.h"
            "components/torch/torch.c"
            "components/sntp/sntp.h"
            "components/sntp/sntp.c"
            "components/telegram/telegram.h"
            "components/telegram/telegram.c"
            "components/motion/motion.c"
            "components/motion/motion_receiver.c"
            "components/motion/motion.h"
            "components/bus/bus.h"
            "components/bus/bus.c"
            "components/bus/handlers/handlers.h"
            "components/bus/handlers/telegram.c"
            "components/http_client/http_client.c"
            "components/http_client/http_client.h"
            "components/http_server/http_server.c"
            "components/http_server/http_server.h"
            "components/http_server/http_helper/http_helper.c"
            "components/http_server/http_helper/http_helper.h"
            "components/http_server/actions/actions.h"
            "components/http_server/actions/capture_action.c"
            "components/http_server/actions/stream_action.c"
            "components/http_server/actions/save_image_action.c"
            "components/http_server/actions/index_action.c"
            "components/http_server/actions/cmd_camera_action.c"
            "components/http_server/actions/status_camera_action.c"
            "components/http_server/actions/record_action.c"
            "components/http_server/actions/sse_action.c"
            "components/http_server/actions/ws_action.c"
            "components/video/avi_writer.c"
            "components/video/avi_writer.h"
            "components/video/video.c"
            "components/video/video.h"
        INCLUDE_DIRS
            "."
            "components/config"
        EMBED_FILES
            "components/http_server/web/index.html"
        REQUIRES
            esp_wifi
            esp_http_server
            esp_http_client
            fatfs
            sdmmc
            driver
            esp_psram
            esp_timer
            nvs_flash
            esp_event
            esp_netif
            espressif__esp32-camera
            espressif__esp_jpeg
            log
            freertos
            esp_https_ota
            esp_http_client
            esp_hw_support
            mbedtls
)
target_compile_definitions(${COMPONENT_LIB} PRIVATE -DPROJECT_VER="${PROJECT_VER}")